apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-persistent-volume
  namespace: dev
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
